name: flurine_lambda
description: A starting point for Dart libraries or applications.
version: 0.9.3
homepage: http://github.com/dhaval15/flurine_lambda

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  petitparser: ^3.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
