name: flurine_lambda
description: A starting point for Dart libraries or applications.
version: 0.9.3+2
homepage: http://github.com/dhaval15/flurine_lambda

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  petitparser: ^3.0.2
